### ISSUE TITLE
[Bug Report] incorrect move counts

### ISSUE THREAD

**Issue by kolung** [jaimeenahn/goHomeBulls#148]
https://gyazo.com/6ba85ac7a90dfd83690b58fe2090e536

At this time, when I press ↓ button, the count of moves shouldn't increase. Instead, it should stay the same since the character can not move to the wall.

**Comment by dongkyul** [comment]
We deliberately made like that. Since the rank will be decided based on move counts (less is better), we put the intention for user's mistakenly moving. Users will be careful moving with that situation and the game would be more fun. Besides, if we do not have that function, high rank would be easily decided.
