### ISSUE TITLE
[bug]The webpage go up and down while push the bull,press 'r' is not working

### ISSUE THREAD

**Issue by suhuboice** [jaimeenahn/goHomeBulls#152]
1. The webpage go up and down while push the bull.
2. press 'r' is not working

**Comment by zhaosec** [comment]
The pages scrolling is because your screen resolution has zoomed-out the game page. You will have to zoom-in your screen to make sure the page stationary. 
As we state in the MVP, " If stamina become zero, the game will be finished automatically Stamina drinks will show up randomly in each stages. Therefore, maintaining stamina is the key." If you run out of stamina the game cannot be reset.
